name: dart_helpers
description: Helpers for Dart's development. See also `flutter_helpers`.
homepage: https://github.com/signmotion/dart_helpers
publish_to: none

version: 0.1.0+100

environment:
  sdk: ">=3.0.6"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  path: ^1.8.3
  vector_math: ^2.1.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
