name: dart_helpers
description: Helpers for Dart's development. See also `flutter_helpers`.
homepage: https://github.com/signmotion/dart_helpers
publish_to: none

version: 0.1.0+100

environment:
  sdk: ">=3.2.3"

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  path: ^1.9.0
  strings: ^2.0.3
  vector_math: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
