name: dart_helpers
description: Helpers for Dart's development. See also `flutter_helpers`.
homepage: https://github.com/signmotion/dart_helpers
publish_to: none

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ">=1.18.0 <2.0.0"
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  json_dart: ^0.1.0
  path: ^1.8.3
  strings: ^3.0.0
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
